using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using Repository.Pattern.Ef6;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccess.Models
{
    public partial class NWEntities : DataContext
    {
        public NWEntities() : base("name=NWEntities"){}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }

        public virtual DbSet<Category> Categories { get; set; } 
        public virtual DbSet<CustomerCustomerDemo> CustomerCustomerDemo { get; set; } 
        public virtual DbSet<CustomerDemographic> CustomerDemographics { get; set; } 
        public virtual DbSet<Customer> Customers { get; set; } 
        public virtual DbSet<Employee> Employees { get; set; } 
        public virtual DbSet<EmployeeTerritory> EmployeeTerritories { get; set; } 
        public virtual DbSet<OrderDetail> OrderDetails { get; set; } 
        public virtual DbSet<Order> Orders { get; set; } 
        public virtual DbSet<Product> Products { get; set; } 
        public virtual DbSet<Region> Region { get; set; } 
        public virtual DbSet<Shipper> Shippers { get; set; } 
        public virtual DbSet<Supplier> Suppliers { get; set; } 
        public virtual DbSet<Territory> Territories { get; set; }     }
}

