//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated from a template.
    //
    //     Manual changes to this file may cause unexpected behavior in your application.
    //     Manual changes to this file will be overwritten if the code is regenerated.
    //
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web.Http;
using ODataV4 = System.Web.OData;
using DataAccess.Models;

namespace WebAPI
{
        public static class ODataRegistrations
    {
        public static void Register(ODataV4.Builder.ODataModelBuilder builder4)
        { 
                builder4.EntitySet<Category>("Categories");
                builder4.EntitySet<CustomerCustomerDemo>("CustomerCustomerDemo");
                builder4.EntitySet<CustomerDemographic>("CustomerDemographics");
                builder4.EntitySet<Customer>("Customers");
                builder4.EntitySet<Employee>("Employees");
                builder4.EntitySet<EmployeeTerritory>("EmployeeTerritories");
                builder4.EntitySet<OrderDetail>("OrderDetails");
                builder4.EntitySet<Order>("Orders");
                builder4.EntitySet<Product>("Products");
                builder4.EntitySet<Region>("Region");
                builder4.EntitySet<Shipper>("Shippers");
                builder4.EntitySet<Supplier>("Suppliers");
                builder4.EntitySet<Territory>("Territories");    			;
        }
    }

}
